###############
# DEVELOPMENT #
###############
FROM node:20-alpine

ARG SOURCE=../

# create the appropriate directories
# ENV HOME=/app
ENV APP_HOME=/app/frontend
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# 
COPY ./package*.json ./
RUN yarn install

# copy project
# COPY $SOURCE/frontend $APP_HOME


