###############
# DEVELOPMENT #
###############

# pull official base image
FROM python:3.9.6-alpine

ARG SOURCE=../

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update 
RUN apk add -y --no-cache\
    postgresql-dev\
    gcc\
    python3-dev\
    musl-dev\
    build-base\
    linux-headers\
    tmux\
    vim\
    bush\
    zsh
RUN  apk cache clean

# install dependencies
COPY $SOURCE/requirements/common.txt /tmp/common.txt
COPY $SOURCE/requirements/development.txt /tmp/development.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/development.txt

# create the appropriate directories
ENV APP_HOME=/app/backend
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# copy project
COPY $SOURCE/backend $APP_HOME