version: '3.8'

volumes:
  db_prod:
  static:
  media:
  
services:
  app:
    container_name: app-nansy
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile.back 
    working_dir: /app/backend
    env_file:
      - ./env/prod/.env
    volumes:
      - static:/app/backend/static
      - media:/app/backend/media
    command: 
      - sh
      - -c
      - |
        sleep 5s
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        gunicorn portal.wsgi:application --bind 0.0.0.0:8000      
    expose:
      - 8000    
    depends_on:
      - db  
    networks:
      - db-net
      - backend


  db:
    image: postgres:14.3-alpine
    container_name: db
    volumes:
      - db_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./env/production/.db.env
    networks:
      - db-net
  

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static:/app/backend/static
      - media:/app/backend/media
    restart: always

networks:
  backend:
    driver: bridge
  db-net:
    driver: bridge
